### ISSUE TITLE
copyright notice/disclaimer at the top of every source code file

### ISSUE THREAD

**Issue by mkuzak** [NLeSC/estep-checklist#23]
I'm in favor of getting rid of those, since they are not required. Unless someone thinks we need it.

**Comment by sverhoeven** [comment]
If the source code file is or can be distributed alone then the notice should be there. 
If the source code file is always distributed with a LICENSE file, etc. then the notice can be removed.

@LourensVeen what do you think?

**Comment by jiskattema** [comment]
if i remember correctly, they are not (legally) necessary
How about only leaving them in if the license is not our preferred license, and redistribution is _likely_?

**Comment by mkuzak** [comment]
I agree with @sverhoeven on that, if the files are likely to be distributed separately they should have notice on top, otherwise not.

**Comment by LourensVeen** [comment]
It's not legally necessary. When you create a work you get to own the copyright, whether you put any notices on it or not (according to the Berne convention, which almost all nations are signatory to). If you don't have a statement in every file and somehow a file gets separated from the rest, then whoever gets it would not know that it's licensed, and therefore should not distribute it. If they can somehow ascertain that it's ASLv2, then they can safely distribute it, as long as they put the license notice back in, since the license requires that.

Of course, having such a notice prevents a lot of hassle in such a case, but I agree that in practice this probably doesn't happen often, and especially in short files it's not nice to have such a big block of text repeated everywhere.

Both the FSF and the ASF recommend putting a rather lengthy notice into every file, with a restatement of the warranty disclaimer. I've never heard of anyone suing anyone over a warranty issue with free software however, and I can't imagine a judge ruling that we're responsible for warranty on a free-of-cost piece of software licensed under a license that explicitly disclaims warranty, just because it wasn't restated in every single file. (If someone pays us to develop software for them, then we will probably be required to provide warranty regardless of what the license says, but that's a separate issue.)

Perhaps we can use a shortened version, something like this:

Copyright 2014, 2016 Netherlands eScience Center.
Licensed under the Apache License, version 2.0. See LICENSING for details.

The LICENSING file could then contain the longer statement, together with the actual license text, or something more complicated if the program consists of multiple modules with different licenses.

Anyone wanting to reuse a single file from our program would then be responsible for doing so according to the license, e.g. by having their own LICENSING file that explains that we own that particular file and contains the license, or by adding the longer statement to the file, or in some other way that the license we used allows. 

Since there is at least a statement of who owns the copyright, if someone happens to come across a single file, they at least know that it's copyrighted (and can't claim they thought it was public domain) and they can contact us if there's any doubt as to what happened and what they are and aren't allowed to do.

**Comment by larsmans** [comment]
Agree with @LourensVeen on including that short notice. Program modules get copied around when users want only part of the functionality.

**Comment by mkuzak** [comment]
What will we do in case of files with external contributions. We'd have to ask people to transfer their copyrights to NLeSC. We should have some standard form for that too

**Comment by LourensVeen** [comment]
Not necessarily, the copyright could be shared. The contributors do have to explicitly contribute under Apache 2.0, but the license already contains language that says that all contributions are considered to be under Apache 2.0 as well.

Of course, this will make it more difficult to relicense the code, because all contributors have to give permission. This is more of a governance matter than a licensing matter though.

**Comment by mkuzak** [comment]
migrated to https://github.com/NLeSC/guide/issues/8
